### PR TITLE
Azerite Bar functionality and other improvements

### PR DESCRIPTION
**Pull request by VasiliyZhushma**
[+] Azerite Bar display for max level + configuration
[+] Russian translation
[*] 50% transparency for bubbles

### CODE REVIEW

**Comment by VasiliyZhushma** [comment]
Known issue for Russian translation: bar is not displayed upon player login, only after /reload

**Comment by VasiliyZhushma** [comment]
> Known issue for Russian translation: bar is not displayed upon player login, only after /reloa

Fixed in 2nd commit

**Comment by phyber** [comment]
Apologies, I've only just noticed this PR.
I'll check this out in a while, thanks.

**Comment by phyber** [comment]
Merged, thanks for this, and sorry for the length of time it took. A new tag will be pushed shortly with these and a few other changes.

**Pull request merged**
